### ISSUE TITLE
Add sender address to the data streamed by the udpSource

### ISSUE THREAD

**Issue by mihaigiurgeanu** [kqr/udp-conduit#3]
If multiple hosts are sending messages to the udpSource, the udpSource will just stream the messages to the downstream components and the downstream components will have no idea of who send them the data, unless the message will contain some sender identification.

Would be useful for high speed protocols to be able to identify the sender by its ip address, without including specific identification fields into the protocol.

I propose changing the `udpSource` to strea pairs `(ByteString, SockAddr)` instead of just `ByteString`, and adding a new source `udpSourcePlain` that will simply stream the `ByteString` without the sender's address.

**Comment by kqr** [comment]
These ideas make a lot of sense and your PR #4 is a good implementation of these ideas. I'll close this once the PR can be merged!

**Comment by kqr** [comment]
Closing this since #4 has been merged!
